name: Node.js Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
        
      - name: Check for required test file
        run: |
          if [ -f "test-file.txt" ]; then
            echo "Required test file exists"
          else
            echo "Error: test-file.txt is missing"
            exit 1
          fi
      
      - name: Run tests
        run: npm test